# Generated by Django 6.0.4 on 2026-05-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.CharField(blank=True, help_text='Volume da embalagem, ex: 50ml, 100ml', max_length=20),
        ),
    ]
