# Generated by Django 6.0.4 on 2026-05-02 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produto_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, help_text='Preço de custo por unidade (opcional)', max_digits=10, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='loja.produto')),
            ],
            options={
                'verbose_name': 'Entrada de Stock',
                'verbose_name_plural': 'Entradas de Stock',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('motivo', models.CharField(choices=[('venda', 'Venda'), ('perda', 'Perda / Dano'), ('devolucao', 'Devolução'), ('outro', 'Outro')], default='venda', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='loja.produto')),
            ],
            options={
                'verbose_name': 'Saída de Stock',
                'verbose_name_plural': 'Saídas de Stock',
                'ordering': ['-data'],
            },
        ),
    ]
