# Generated by Django 6.0.4 on 2026-05-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_entrada_saida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('bi', models.CharField(help_text='Número do Bilhete de Identidade', max_length=50, unique=True, verbose_name='Nº BI')),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cargo', models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('operador', 'Operador'), ('vendedor', 'Vendedor'), ('armazem', 'Armazém')], default='operador', max_length=20)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], default='integral', max_length=10)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, help_text='Salário mensal em Kz', max_digits=12, null=True)),
                ('data_admissao', models.DateField(help_text='Data de entrada na empresa')),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
    ]
