# Generated by Django 6.0.4 on 2026-05-02 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_funcionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='utilizador',
            field=models.OneToOneField(blank=True, help_text='Conta de utilizador associada (apenas para funcionários activos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to=settings.AUTH_USER_MODEL),
        ),
    ]
