# Generated by Django 6.0.4 on 2026-05-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_funcionario_utilizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Data de nascimento do funcionário', null=True),
        ),
    ]
