# Generated by Django 6.0.4 on 2026-05-02 20:15

import loja.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_funcionario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='bi',
            field=models.CharField(help_text='Formato: 9 dígitos + 2 letras + 3 dígitos (ex: 003456789LA045)', max_length=20, unique=True, validators=[loja.models.validar_bi_angola], verbose_name='Nº BI'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(help_text='Formato: 9XX XXX XXX', max_length=20, validators=[loja.models.validar_telefone_angola]),
        ),
    ]
