# Generated by Django 6.0.4 on 2026-05-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_funcionario_bi_alter_funcionario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('operador', 'Operador'), ('vendedor', 'Vendedor'), ('armazem', 'Armazém')], default='operador', max_length=20),
        ),
    ]
