# Generated by Django 6.0.4 on 2026-05-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='EAN-13, EAN-8, Code 128, QR Code, etc.', max_length=100, null=True, unique=True),
        ),
    ]
