# Generated by Django 6.0.4 on 2026-05-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_produto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='essencia',
            field=models.TextField(blank=True, help_text='Notas olfativas: topo, coração e fundo (ex: Bergamota, Jasmim, Sândalo)'),
        ),
    ]
