# Generated by Django 6.0.4 on 2026-05-02 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_alter_encomenda_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='vendido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to=settings.AUTH_USER_MODEL, verbose_name='Vendido por'),
        ),
    ]
