# Generated by Django 6.0.4 on 2026-05-03 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_encomenda_vendido_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('categoria', models.CharField(choices=[('venda', 'Venda'), ('reforco', 'Reforço de Caixa'), ('investimento', 'Investimento'), ('outro_ganho', 'Outro Ganho'), ('despesa', 'Despesa Operacional'), ('salario', 'Salário'), ('renda', 'Renda / Aluguer'), ('utilidades', 'Água / Luz / Internet'), ('fornecedor', 'Pagamento a Fornecedor'), ('imposto', 'Imposto / Taxa'), ('manutencao', 'Manutenção'), ('outro_custo', 'Outro Custo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento de Caixa',
                'verbose_name_plural': 'Movimentos de Caixa',
                'ordering': ['-data'],
            },
        ),
    ]
