# Generated by Django 6.0.4 on 2026-05-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_movimentocaixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saida',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='Saida',
        ),
    ]
