# Generated by Django 6.0.4 on 2026-05-03 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_remove_saida_produto_delete_entrada_delete_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocaixa',
            name='encomenda',
            field=models.ForeignKey(blank=True, help_text='Venda associada (preenchido automaticamente para entradas de venda).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='loja.encomenda'),
        ),
    ]
