# Generated by Django 6.0.4 on 2026-05-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_precos_lucro'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/', verbose_name='Foto'),
        ),
    ]
