# Generated by Django 6.0.4 on 2026-05-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_funcionario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('referer', models.URLField(blank=True)),
                ('sessao', models.CharField(blank=True, db_index=True, max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Visita ao Site',
                'verbose_name_plural': 'Visitas ao Site',
                'ordering': ['-criado_em'],
            },
        ),
    ]
