# Generated by Django 6.0.4 on 2026-05-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0018_visitasite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('dia', 'Dia comemorativo'), ('semana', 'Semana temática'), ('mes', 'Mês temático'), ('campanha', 'Campanha pontual')], default='dia', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('desconto_percentagem', models.PositiveIntegerField(default=0, help_text='Percentagem de desconto associada (0 a 100). 0 = sem desconto automático.')),
                ('cor', models.CharField(default='amber', help_text='Cor de destaque (amber, rose, sky, emerald, violet, stone).', max_length=20)),
                ('icone', models.CharField(blank=True, default='🎁', help_text='Emoji ou ícone curto.', max_length=10)),
                ('recorrente_anual', models.BooleanField(default=True, help_text='Se marcado, repete-se todos os anos nas mesmas datas.')),
                ('activo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'ordering': ['data_inicio', 'nome'],
            },
        ),
    ]
