# Generated by Django 6.0.4 on 2026-05-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0020_seed_promocoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAniversario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_cliente', models.TextField(default='Olá {nome}! 🎉\n\nA equipa Décent Privé deseja-lhe um feliz aniversário cheio de fragrâncias e momentos especiais. Que este novo ano lhe traga muita saúde, alegria e perfume!\n\n{brinde}Com carinho,\nDécent Privé Perfumaria', help_text='Use {nome} e {brinde} como marcadores.')),
                ('mensagem_funcionario', models.TextField(default='Parabéns, {nome}! 🥂\n\nToda a família Décent Privé deseja-lhe um feliz aniversário. Obrigado por fazer parte desta equipa e por ajudar a perfumar o dia a dia dos nossos clientes.\n\n{brinde}Um forte abraço,\nDirecção Décent Privé', help_text='Use {nome} e {brinde} como marcadores.')),
                ('hora_envio', models.TimeField(default='10:00', help_text='Hora a que as felicitações são enviadas.')),
                ('enviar_email', models.BooleanField(default=True)),
                ('enviar_sms', models.BooleanField(default=True)),
                ('brinde_activo', models.BooleanField(default=False, help_text='Oferecer brinde no aniversário.')),
                ('brinde_descricao', models.CharField(blank=True, default='Como presente, oferecemos-lhe 10% de desconto em qualquer compra durante o seu mês de aniversário.', help_text='Texto incluído na mensagem quando o brinde estiver activo.', max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='Ligar/desligar todo o sistema de felicitações.')),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Aniversários',
                'verbose_name_plural': 'Configuração de Aniversários',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Data de nascimento do cliente', null=True),
        ),
        migrations.CreateModel(
            name='FelicitacaoEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionário')], max_length=20)),
                ('pessoa_id', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS / WhatsApp'), ('manual', 'Manual')], max_length=20)),
                ('sucesso', models.BooleanField(default=True)),
                ('erro', models.CharField(blank=True, max_length=300)),
                ('ano', models.PositiveIntegerField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Felicitação Enviada',
                'verbose_name_plural': 'Felicitações Enviadas',
                'ordering': ['-enviado_em'],
                'indexes': [models.Index(fields=['tipo', 'pessoa_id', 'ano'], name='loja_felici_tipo_9a7b74_idx')],
            },
        ),
    ]
