# Generated by Django 6.0.4 on 2026-05-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0021_configaniversario_cliente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configaniversario',
            name='horario_aleatorio',
            field=models.BooleanField(default=False, help_text='Se activo, cada pessoa recebe a uma hora aleatória dentro da janela definida.'),
        ),
        migrations.AddField(
            model_name='configaniversario',
            name='janela_fim',
            field=models.TimeField(default='18:00', help_text='Fim da janela de envio (modo aleatório).'),
        ),
        migrations.AddField(
            model_name='configaniversario',
            name='janela_inicio',
            field=models.TimeField(default='09:00', help_text='Início da janela de envio (modo aleatório).'),
        ),
        migrations.AlterField(
            model_name='configaniversario',
            name='hora_envio',
            field=models.TimeField(default='10:00', help_text='Hora a que as felicitações são enviadas (modo fixo).'),
        ),
    ]
