# Generated by Django 6.0.4 on 2026-05-03 15:12

from django.db import migrations, models
from django.utils.text import slugify


def gerar_slugs(apps, schema_editor):
    Promocao = apps.get_model('loja', 'Promocao')
    usados = set()
    for p in Promocao.objects.all():
        base = slugify(p.nome)[:130] or f'promocao-{p.pk}'
        slug = base
        n = 2
        while slug in usados:
            slug = f'{base}-{n}'
            n += 1
        usados.add(slug)
        p.slug = slug
        p.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0022_configaniversario_horario_aleatorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem para o carrossel e cabeçalho da promoção.', null=True, upload_to='promocoes/'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='link_botao',
            field=models.CharField(blank=True, help_text='Deixe em branco para usar a página automática da promoção.', max_length=200),
        ),
        migrations.AddField(
            model_name='promocao',
            name='mostrar_carrossel',
            field=models.BooleanField(default=False, help_text='Apresentar como slide no carrossel da página inicial.'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='mostrar_landing',
            field=models.BooleanField(default=False, help_text='Apresentar como secção/colecção na página inicial e em /colecções.'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='produtos',
            field=models.ManyToManyField(blank=True, help_text='Produtos abrangidos por esta promoção.', related_name='promocoes', to='loja.produto'),
        ),
        migrations.AddField(
            model_name='promocao',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True),
        ),
        migrations.RunPython(gerar_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='promocao',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AddField(
            model_name='promocao',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Linha curta exibida acima do título no carrossel.', max_length=200),
        ),
        migrations.AddField(
            model_name='promocao',
            name='texto_botao',
            field=models.CharField(default='Ver Promoção', max_length=50),
        ),
    ]
