# Generated by Django 6.0.4 on 2026-05-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0023_promocao_imagem_promocao_link_botao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome (opcional)')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de inscrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Inscrição na Newsletter',
                'verbose_name_plural': 'Inscrições na Newsletter',
                'ordering': ['-data_inscricao'],
            },
        ),
    ]
