# Generated by Django 6.0.5 on 2026-05-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0024_newsletterinscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='forma_pagamento',
            field=models.CharField(choices=[('avista', 'À Vista'), ('parcelado', 'Parcelado (2x)')], default='avista', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='parcela1_paga',
            field=models.BooleanField(default=False, verbose_name='1ª Parcela Paga'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='parcela2_paga',
            field=models.BooleanField(default=False, verbose_name='2ª Parcela Paga'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='valor_parcela1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Primeira parcela (mínimo 50% do total)', max_digits=10, null=True, verbose_name='Valor 1ª Parcela'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='valor_parcela2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor 2ª Parcela'),
        ),
    ]
