# Generated by Django 6.0.5 on 2026-05-21 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0025_encomenda_forma_pagamento_encomenda_parcela1_paga_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Compra/Recebimento)'), ('saida', 'Saída (Venda)'), ('devolucao', 'Devolução'), ('ajuste', 'Ajuste Manual')], max_length=20)),
                ('quantidade', models.IntegerField(help_text='Positivo para entrada, negativo para saída')),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_stock', to=settings.AUTH_USER_MODEL)),
                ('encomenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_stock', to='loja.encomenda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_stock', to='loja.produto')),
            ],
            options={
                'verbose_name': 'Movimento de Stock',
                'verbose_name_plural': 'Movimentos de Stock',
                'ordering': ['-criado_em'],
            },
        ),
    ]
