# Generated by Django 6.0.5 on 2026-05-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0026_movimentostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='data_proxima_parcela',
            field=models.DateField(blank=True, help_text='Data prevista para o pagamento da próxima parcela', null=True, verbose_name='Data da Próxima Parcela'),
        ),
    ]
