# Generated by Django 6.0.5 on 2026-05-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0027_encomenda_data_proxima_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='origem',
            field=models.CharField(choices=[('balcao', 'Balcão'), ('online', 'Online')], default='balcao', help_text='Indica se a venda foi feita no balcão ou online', max_length=20, verbose_name='Origem da Encomenda'),
        ),
    ]
