# Generated by Django 6.0.5 on 2026-05-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0028_encomenda_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, help_text='Explicação do motivo do cancelamento da venda', null=True, verbose_name='Motivo do Cancelamento'),
        ),
    ]
