# Generated by Django 6.0.5 on 2026-06-22 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0036_loteimportacao_itemloteimportacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('operador_caixa', 'Operador de Caixa'), ('seguranca', 'Segurança'), ('limpeza', 'Limpeza')], default='operador', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagamentosalario',
            name='custo_inss_patronal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Contribuição da entidade patronal: 8% do bruto. Custo da empresa, não deduzido do salário.', max_digits=12, verbose_name='INSS Patronal (Kz)'),
        ),
        migrations.AlterField(
            model_name='pagamentosalario',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, help_text='Snapshot do salário base na altura do processamento.', max_digits=12, verbose_name='Salário Base (Kz)'),
        ),
        migrations.AlterField(
            model_name='pagamentosalario',
            name='salario_bruto',
            field=models.DecimalField(decimal_places=2, help_text='Salário base + comissão.', max_digits=12, verbose_name='Salário Bruto (Kz)'),
        ),
        migrations.AlterField(
            model_name='pagamentosalario',
            name='taxa_inss',
            field=models.DecimalField(decimal_places=2, default=3, help_text='Em Angola, a contribuição do trabalhador para o INSS é 3% do bruto.', max_digits=5, verbose_name='Taxa INSS Trabalhador (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Segmento livre: Nicho, Designer, Lançamentos, etc. (gerido em Categorias)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='loja.categoria'),
        ),
    ]
