# Generated by Django 6.0.5 on 2026-06-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0037_alter_funcionario_cargo_and_more'),
        ('loja', '0037_imagem_galeria'),
    ]

    operations = [
    ]
