# Generated by Django 6.0.5 on 2026-06-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0039_encomenda_tipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('operador_caixa', 'Operador de Caixa'), ('seguranca', 'Segurança'), ('limpeza', 'Limpeza')], default='operador_caixa', max_length=20),
        ),
    ]
