# Generated by Django 6.0.5 on 2026-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0040_fix_funcionario_cargo_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desconto_percentagem',
            field=models.PositiveIntegerField(default=0, help_text='Percentagem de desconto para promoções directas no produto (0 = sem desconto).'),
        ),
    ]
