# Generated by Django 6.0.5 on 2026-06-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0041_add_desconto_percentagem_to_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código do cupão (ex: VERAO20)', max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(blank=True, help_text='Nota interna sobre o cupão', max_length=200, verbose_name='Descrição')),
                ('tipo_desconto', models.CharField(choices=[('percentagem', 'Percentagem'), ('valor', 'Valor Fixo (Kz)')], default='percentagem', max_length=15, verbose_name='Tipo de Desconto')),
                ('valor_desconto', models.DecimalField(decimal_places=2, help_text='Percentagem (1-100) ou valor fixo em Kz', max_digits=10, verbose_name='Valor do Desconto')),
                ('valor_minimo_compra', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo do carrinho para o cupão ser válido (0 = sem mínimo)', max_digits=10, verbose_name='Valor Mínimo de Compra')),
                ('limite_uso', models.PositiveIntegerField(default=0, help_text='Número máximo de utilizações (0 = ilimitado)', verbose_name='Limite de Usos')),
                ('usos', models.PositiveIntegerField(default=0, verbose_name='Utilizações')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Activo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupão',
                'verbose_name_plural': 'Cupões',
                'ordering': ['-criado_em'],
            },
        ),
    ]
