# Generated by Django 6.0.5 on 2026-06-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0042_cupao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupao',
            name='produtos',
            field=models.ManyToManyField(blank=True, help_text='Se vazio, aplica-se a todo o carrinho. Se seleccionado, apenas a esses produtos.', to='loja.produto', verbose_name='Produtos'),
        ),
    ]
