# Generated by Django 6.0.5 on 2026-06-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0043_cupao_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='origem',
            field=models.CharField(blank=True, choices=[('europeu', 'Europeu'), ('oriental', 'Oriental')], default='europeu', help_text='Origem do perfume: Europeu ou Oriental.', max_length=20, verbose_name='Origem'),
        ),
    ]
