# Generated by Django 6.0.5 on 2026-07-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0044_add_origem_to_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='data_emissao',
            field=models.DateTimeField(blank=True, help_text='Data/hora de finalização, usada na assinatura digital do documento', null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='hash_anterior',
            field=models.TextField(blank=True, help_text='Assinatura do documento fiscal imediatamente anterior na cadeia', null=True, verbose_name='Hash do Documento Anterior'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='hash_atual',
            field=models.TextField(blank=True, help_text='Assinatura RSA/SHA-256 deste documento, encadeada ao anterior', null=True, verbose_name='Assinatura Digital (Hash)'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='hash_curto',
            field=models.CharField(blank=True, help_text='4 caracteres (posições 1ª, 11ª, 21ª, 31ª da assinatura) impressos no documento', max_length=4, null=True, verbose_name='Hash Curto'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='numero_documento',
            field=models.CharField(blank=True, db_index=True, help_text='Numeração sequencial por série/ano, ex: FT 2026/145', max_length=30, null=True, unique=True, verbose_name='Número do Documento Fiscal'),
        ),
    ]
