# Generated by Django 6.0.5 on 2026-07-20 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0045_encomenda_data_emissao_encomenda_hash_anterior_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_falhado', 'Login Falhado'), ('emissao', 'Emissão de Documento Fiscal'), ('cancelamento', 'Cancelamento de Documento Fiscal'), ('rectificacao', 'Rectificação (Nota de Crédito)'), ('exportacao_saft', 'Exportação SAF-T'), ('backup', 'Backup'), ('configuracao', 'Alteração de Configuração'), ('outra', 'Outra')], max_length=30)),
                ('descricao', models.CharField(max_length=500)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registo de Auditoria',
                'verbose_name_plural': 'Registos de Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Número do Documento')),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(choices=[('anulacao', 'Anulação Total'), ('correcao', 'Correção Parcial'), ('devolucao', 'Devolução de Mercadoria'), ('desconto', 'Desconto Posterior')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hash_anterior', models.TextField(blank=True, null=True)),
                ('hash_atual', models.TextField(blank=True, null=True)),
                ('hash_curto', models.CharField(blank=True, max_length=4, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_emitidas', to=settings.AUTH_USER_MODEL)),
                ('factura_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='loja.encomenda', verbose_name='Factura Original')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='RegistoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha')], max_length=20)),
                ('ficheiro', models.CharField(blank=True, max_length=500)),
                ('tamanho_bytes', models.BigIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('efectuado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registo de Backup',
                'verbose_name_plural': 'Registos de Backups',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='SerieDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(choices=[('FT', 'Factura'), ('NC', 'Nota de Crédito'), ('ND', 'Nota de Débito'), ('FR', 'Factura Recibo')], db_index=True, max_length=10)),
                ('ano', models.PositiveIntegerField(db_index=True)),
                ('numero_actual', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Série Documental',
                'verbose_name_plural': 'Séries Documentais',
                'ordering': ['-ano', 'serie'],
                'constraints': [models.UniqueConstraint(fields=('serie', 'ano'), name='serie_ano_unico')],
            },
        ),
    ]
