# Generated by Django 6.0.5 on 2026-07-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0046_agt_compliance_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceitar_numerario', models.BooleanField(default=True, verbose_name='Aceitar Numerário à Entrega')),
                ('aceitar_transferencia', models.BooleanField(default=True, verbose_name='Aceitar Transferência Bancária')),
                ('banco_nome', models.CharField(blank=True, max_length=100, verbose_name='Nome do Banco')),
                ('banco_titular', models.CharField(blank=True, max_length=150, verbose_name='Titular da Conta')),
                ('banco_iban', models.CharField(blank=True, max_length=30, verbose_name='IBAN')),
                ('aceitar_paypay', models.BooleanField(default=False, verbose_name='Aceitar Paypay')),
                ('paypay_numero', models.CharField(blank=True, max_length=30, verbose_name='Número Paypay')),
                ('gateway_activo', models.BooleanField(default=False, help_text='Só entra em funcionamento se o Entity ID e o Token GPO estiverem preenchidos.', verbose_name='Activar Multicaixa Express (Online)')),
                ('emis_ambiente', models.CharField(choices=[('sandbox', 'Sandbox (testes)'), ('producao', 'Produção')], default='sandbox', max_length=10, verbose_name='Ambiente EMIS')),
                ('emis_entity_id', models.CharField(blank=True, help_text='Fornecido pela EMIS ao registar o comércio no GPO.', max_length=100, verbose_name='Entity ID (EMIS)')),
                ('emis_gpo_token', models.CharField(blank=True, help_text='Chave secreta do GPO — nunca partilhe este valor.', max_length=200, verbose_name='Token GPO (EMIS)')),
                ('emis_callback_secret', models.CharField(blank=True, help_text='Usada para validar as notificações (webhook) recebidas da EMIS.', max_length=200, verbose_name='Chave de Verificação do Callback')),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Pagamentos',
                'verbose_name_plural': 'Configuração de Pagamentos',
            },
        ),
        migrations.AddField(
            model_name='encomenda',
            name='metodo_pagamento',
            field=models.CharField(choices=[('numerario', 'Numerário à Entrega'), ('transferencia', 'Transferência Bancária'), ('multicaixa_express', 'Multicaixa Express (Online)'), ('paypay', 'Paypay')], default='numerario', help_text='Como o cliente pretende pagar (numerário, transferência, Multicaixa Express, Paypay).', max_length=30, verbose_name='Método de Pagamento'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='referencia_pagamento_gateway',
            field=models.CharField(blank=True, help_text='Identificador/referência devolvido pelo gateway de pagamento online (ex: EMIS GPO).', max_length=100, null=True, verbose_name='Referência do Gateway'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='status_pagamento_gateway',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('falhado', 'Falhado')], default='pendente', max_length=20, verbose_name='Estado do Pagamento Online'),
        ),
    ]
