# Generated by Django 6.0.5 on 2026-07-21 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0048_sincronizar_stock_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do cliente')),
                ('notificado', models.BooleanField(default=False, verbose_name='Já notificado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_notificacao', to='loja.produto')),
            ],
            options={
                'verbose_name': 'Pedido de Notificação de Stock',
                'verbose_name_plural': 'Pedidos de Notificação de Stock',
                'ordering': ['-criado_em'],
                'unique_together': {('produto', 'email')},
            },
        ),
    ]
