"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carregar variáveis do ficheiro .env (se python-dotenv estiver instalado)
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-+95nr4rz5g7)a&it4(qxpck!11!)ofgao*ixf)x-y_xlj-o9mq',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = ['decentprive.ao','www.decentprive.ao','gestao.decentprive.ao','127.0.0.1']

# ---------------------------------------------------------------------------
# Segurança de produção
# ---------------------------------------------------------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'tailwind',
    'theme',
    'loja',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'loja.context_processors.encomendas_online_pendentes',
                'loja.context_processors.nivel_acesso',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-pt'

TIME_ZONE = 'Africa/Luanda'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

TAILWIND_APP_NAME = 'theme'
NPPM_BIN_PATH = r'C:\Program Files\nodejs\npm.cmd'

# ---------------------------------------------------------------------------
# Email (envio de credenciais a novos utilizadores)
# ---------------------------------------------------------------------------
# Backend de email — lido do .env.
# Se EMAIL_HOST_USER não estiver definido, cai no backend de consola (desenvolvimento).
_email_user = os.environ.get('EMAIL_HOST_USER', '')

if _email_user:
    EMAIL_BACKEND    = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST       = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT       = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS    = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
    EMAIL_HOST_USER  = _email_user
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL  = os.environ.get(
        'DEFAULT_FROM_EMAIL',
        f'Décent Privé <{_email_user}>'
    )
else:
    # Modo de desenvolvimento — imprime os emails no terminal
    EMAIL_BACKEND      = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'Décent Privé <decentprive@gmail.com>'

# ---------------------------------------------------------------------------
# SMS gateway (opcional)
# ---------------------------------------------------------------------------
# Se SMS_GATEWAY_URL estiver definido, será feito um POST com os campos
# {to, message, api_key} para enviar a mensagem. Caso contrário, o conteúdo
# do SMS é apenas registado nos logs do servidor.
SMS_GATEWAY_URL = os.environ.get('SMS_GATEWAY_URL', '')
SMS_GATEWAY_API_KEY = os.environ.get('SMS_GATEWAY_API_KEY', '')
SMS_SENDER = 'DécentPrive'

# ---------------------------------------------------------------------------
# Sessões
# ---------------------------------------------------------------------------
SESSION_COOKIE_AGE = 900          # 15 minutos (em segundos)
SESSION_SAVE_EVERY_REQUEST = True  # Reinicia o contador a cada pedido
SESSION_COOKIE_SECURE = not DEBUG  # Apenas HTTPS em produção
SESSION_COOKIE_HTTPONLY = True     # Inacessível via JavaScript