from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('newsletter/inscrever/', views.newsletter_inscrever, name='newsletter_inscrever'),
    path('gestao/newsletter/', views.newsletter_gestao, name='newsletter_gestao'),
    path('gestao/newsletter/enviar/', views.gestao_enviar_newsletter, name='gestao_enviar_newsletter'),
    path('', views.home, name='home'),
    path('colecoes/', views.colecoes, name='colecoes'),
    path('produto/<int:pk>/', views.produto_detalhe, name='produto_detalhe'),
    path('promocao/<slug:slug>/', views.promocao_publica, name='promocao_publica'),
    path('encomendas/', views.encomendas, name='encomendas'),
    path('encomendas/sucesso/', views.encomenda_sucesso, name='encomenda_sucesso'),
    path('galeria/', views.galeria, name='galeria'),
    path('fidelidade/', views.fidelidade, name='fidelidade'),
    path('contactos/', views.contactos, name='contactos'),
    # Painel de Gestão
    path('gestao/login/', views.gestao_login, name='gestao_login'),
    path('gestao/logout/', views.gestao_logout, name='gestao_logout'),

    # Recuperação de senha
    path('gestao/recuperar-senha/',
         auth_views.PasswordResetView.as_view(
             template_name='gestao/password_reset.html',
             email_template_name='gestao/password_reset_email.html',
             subject_template_name='gestao/password_reset_subject.txt',
             success_url=reverse_lazy('gestao_password_reset_done'),
         ),
         name='gestao_password_reset'),
    path('gestao/recuperar-senha/enviado/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='gestao/password_reset_done.html',
         ),
         name='gestao_password_reset_done'),
    path('gestao/recuperar-senha/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='gestao/password_reset_confirm.html',
             success_url=reverse_lazy('gestao_password_reset_complete'),
         ),
         name='gestao_password_reset_confirm'),
    path('gestao/recuperar-senha/concluido/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='gestao/password_reset_complete.html',
         ),
         name='gestao_password_reset_complete'),
    path('gestao/', views.gestao_dashboard, name='gestao_dashboard'),
    path('gestao/vendas/', views.gestao_vendas, name='gestao_vendas'),
    path('gestao/vendas/nova/', views.gestao_venda_nova, name='gestao_venda_nova'),
    path('gestao/vendas/<int:pk>/fatura/', views.gestao_fatura, name='gestao_fatura'),
    path('gestao/vendas/<int:pk>/detalhe/', views.gestao_venda_detalhe, name='gestao_venda_detalhe'),
    path('gestao/vendas/<int:pk>/pagamento-parcela2/', views.gestao_registar_pagamento_parcela2, name='gestao_registar_pagamento_parcela2'),
    path('gestao/vendas/<int:pk>/cancelar/', views.gestao_cancelar_encomenda, name='gestao_cancelar_encomenda'),
    path('gestao/encomendas/', views.gestao_encomendas, name='gestao_encomendas'),
    path('gestao/financeiro/entrada/', views.gestao_caixa_entrada, name='gestao_caixa_entrada'),
    path('gestao/financeiro/saida/', views.gestao_caixa_saida, name='gestao_caixa_saida'),
    path('gestao/funcionarios/', views.gestao_funcionarios, name='gestao_funcionarios'),
    path('gestao/funcionarios/novo/', views.gestao_funcionario_criar, name='gestao_funcionario_criar'),
    path('gestao/funcionarios/<int:pk>/editar/', views.gestao_funcionario_criar, name='gestao_funcionario_editar'),
    path('gestao/funcionarios/<int:pk>/apagar/', views.gestao_funcionario_apagar, name='gestao_funcionario_apagar'),
    path('gestao/funcionarios/<int:pk>/criar-utilizador/', views.gestao_funcionario_criar_utilizador, name='gestao_funcionario_criar_utilizador'),
    path('gestao/funcionarios/<int:pk>/', views.gestao_funcionario_detalhe, name='gestao_funcionario_detalhe'),
    path('gestao/produtos/', views.gestao_produtos, name='gestao_produtos'),
    path('gestao/produtos/novo/', views.gestao_produto_criar, name='gestao_produto_criar'),
    path('gestao/produtos/<int:pk>/editar/', views.gestao_produto_criar, name='gestao_produto_editar'),
    path('gestao/produtos/<int:pk>/apagar/', views.gestao_produto_apagar, name='gestao_produto_apagar'),
    path('gestao/produtos/<int:pk>/', views.gestao_produto_detalhe, name='gestao_produto_detalhe'),
    path('gestao/produtos/<int:pk>/entrada-stock/', views.gestao_produto_entrada_stock, name='gestao_produto_entrada_stock'),
    path('gestao/caixa/', views.gestao_caixa, name='gestao_caixa'),
    path('gestao/relatorio/', views.gestao_relatorio, name='gestao_relatorio'),
    path('gestao/relatorio/exportar/', views.gestao_relatorio_exportar_excel, name='gestao_relatorio_exportar_excel'),
    path('gestao/lucro/', views.gestao_lucro, name='gestao_lucro'),
    path('gestao/caixa/exportar/', views.gestao_caixa_exportar_excel, name='gestao_caixa_exportar_excel'),
    path('gestao/salarios/', views.gestao_salarios, name='gestao_salarios'),
    path('gestao/salarios/exportar/', views.gestao_salarios_exportar_excel, name='gestao_salarios_exportar_excel'),
    path('gestao/clientes/', views.gestao_clientes, name='gestao_clientes'),
    path('gestao/clientes/novo/', views.gestao_cliente_criar, name='gestao_cliente_criar'),
    path('gestao/clientes/<int:pk>/editar/', views.gestao_cliente_criar, name='gestao_cliente_editar'),
    path('gestao/clientes/<int:pk>/apagar/', views.gestao_cliente_apagar, name='gestao_cliente_apagar'),
    path('gestao/clientes/<int:pk>/', views.gestao_cliente_detalhe, name='gestao_cliente_detalhe'),
    path('gestao/categorias/', views.gestao_categorias, name='gestao_categorias'),
    path('gestao/categorias/<int:pk>/apagar/', views.gestao_categoria_apagar, name='gestao_categoria_apagar'),
    path('gestao/promocoes/', views.gestao_promocoes, name='gestao_promocoes'),
    path('gestao/promocoes/nova/', views.gestao_promocao_criar, name='gestao_promocao_criar'),
    path('gestao/promocoes/<int:pk>/editar/', views.gestao_promocao_criar, name='gestao_promocao_editar'),
    path('gestao/promocoes/<int:pk>/apagar/', views.gestao_promocao_apagar, name='gestao_promocao_apagar'),
    path('gestao/promocoes/<int:pk>/toggle/', views.gestao_promocao_toggle, name='gestao_promocao_toggle'),
    path('gestao/aniversarios/config/', views.gestao_aniversarios_config, name='gestao_aniversarios_config'),
    path('gestao/aniversarios/<str:tipo>/<int:pk>/enviar/', views.gestao_aniversariante_enviar, name='gestao_aniversariante_enviar'),
    path('gestao/api/barcode/', views.gestao_api_barcode, name='gestao_api_barcode'),
    path('gestao/guia/', views.gestao_guia, name='gestao_guia'),
    path('gestao/galeria/', views.gestao_galeria, name='gestao_galeria'),
    path('gestao/galeria/nova/', views.gestao_galeria_imagem_form, name='gestao_galeria_imagem_nova'),
    path('gestao/galeria/<int:pk>/editar/', views.gestao_galeria_imagem_form, name='gestao_galeria_imagem_editar'),
    path('gestao/galeria/<int:pk>/apagar/', views.gestao_galeria_imagem_apagar, name='gestao_galeria_imagem_apagar'),
    path('gestao/banners/', views.gestao_banners, name='gestao_banners'),
    path('gestao/banners/novo/', views.gestao_banner_form, name='gestao_banner_novo'),
    path('gestao/banners/<int:pk>/editar/', views.gestao_banner_form, name='gestao_banner_editar'),
    path('gestao/banners/<int:pk>/apagar/', views.gestao_banner_apagar, name='gestao_banner_apagar'),
    # Lotes de Importação
    path('gestao/importacoes/', views.gestao_importacoes, name='gestao_importacoes'),
    path('gestao/importacoes/novo/', views.gestao_importacao_criar, name='gestao_importacao_criar'),
    path('gestao/importacoes/<int:pk>/', views.gestao_importacao_detalhe, name='gestao_importacao_detalhe'),
    path('gestao/importacoes/<int:pk>/editar/', views.gestao_importacao_criar, name='gestao_importacao_editar'),
    path('gestao/importacoes/<int:pk>/apagar/', views.gestao_importacao_apagar, name='gestao_importacao_apagar'),
    path('gestao/importacoes/<int:pk>/aplicar-precos/', views.gestao_importacao_aplicar_precos, name='gestao_importacao_aplicar_precos'),
    path('gestao/importacoes/<int:lote_pk>/item/adicionar/', views.gestao_importacao_item_salvar, name='gestao_importacao_item_adicionar'),
    path('gestao/importacoes/<int:lote_pk>/item/<int:item_pk>/editar/', views.gestao_importacao_item_salvar, name='gestao_importacao_item_editar'),
    path('gestao/importacoes/<int:lote_pk>/item/<int:item_pk>/apagar/', views.gestao_importacao_item_apagar, name='gestao_importacao_item_apagar'),
    path('gestao/importacoes/<int:lote_pk>/item/<int:item_pk>/toggle/', views.gestao_importacao_item_toggle, name='gestao_importacao_item_toggle'),
    # Cupões
    path('gestao/cupoes/', views.gestao_cupoes, name='gestao_cupoes'),
    path('gestao/cupoes/novo/', views.gestao_cupao_criar, name='gestao_cupao_novo'),
    path('gestao/cupoes/<int:pk>/editar/', views.gestao_cupao_criar, name='gestao_cupao_editar'),
    path('gestao/cupoes/<int:pk>/apagar/', views.gestao_cupao_apagar, name='gestao_cupao_apagar'),
    path('gestao/cupoes/<int:pk>/toggle/', views.gestao_cupao_toggle, name='gestao_cupao_toggle'),
    # API pública
    path('api/validar-cupao/', views.validar_cupao, name='validar_cupao'),
]